version: '3.7'

services:
  google-authenticator:
    image: google-authenticator
    restart: always
    volumes:
      - ${PWD}/authenticator.data:/root/.authenticator/authenticator.data
      - ${PWD}/server:/usr/bin/server
    ports:
      - "127.0.0.1:48080:8080"

