version: "3.7"

services:
  google-authenticator:
    image: google-authenticator
    restart: always
    volumes:
      - ${PWD}/authenticator/:/root/.authenticator/
    ports:
      - "127.0.0.1:48080:8080"
