version: '3.7'

services:
  google-authenticator:
    image: google-authenticator
    restart: always
    volumes:
      - ${PWD}/authenticator/:/root/.authenticator/
      - ${PWD}/server:/usr/bin/server
      - ${PWD}/ThirdParty/extract_otp_secret_keys:/extract_otp_secret_keys
    ports:
      - "127.0.0.1:48080:8080"

